version: 2
jobs:
  backend:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          _JAVA_OPTIONS: -Xmx2G -Xms256M -Xss2M
    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-cache-{{ checksum "backend/build.sbt" }}
            - sbt-cache-
      - run:
          name: Building backend Project
          working_directory: backend
          command: sbt test:compile
      - save_cache:
          name: Testing backend Project
          paths:
            - ~/.m2
          key: sbt-cache-{{ checksum "backend/build.sbt" }}
          working_directory: backend
      - run:
          name: Testing backend Project
          working_directory: backend
          command: sbt test:test
  frontend:
    docker:
      - image: circleci/node:8-stretch-browsers
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "frontend/package.json" }}
            - npm-cache-
      - run:
          name: Install Local Dependencies
          working_directory: frontend
          command: yarn install
      - save_cache:
          paths:
            - frontend/node_modules
          key: npm-cache-{{ checksum "frontend/package.json" }}
          command: yarn test
workflows:
  version: 2
  run_all:
    jobs:
      - backend
      - frontend
